services:
  reservations:
    build:
      context: .
      dockerfile: ./apps/reservation/Dockerfile
      target: development
    command: "npm run start:dev reservation"
    env_file:
      - ./apps/reservation/.env
    ports:
      - "3002:3002"
      - "4002:3002"
    volumes:
      - .:/usr/src/app
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: "npm run start:dev auth"
    env_file:
      - ./apps/auth/.env
    ports:
      - "3001:3001"
      - "4001:4001"
    volumes:
      - .:/usr/src/app
      
  mongo:
    image: mongo
