services:
  reservations:
    build:
      context: .
      dockerfile: ./apps/reservation/Dockerfile
      target: development
    command: 'npm run start:dev reservation'
    ports:
      - '3002:3002'
      - '4002:3002'
    volumes:
      - .:/usr/src/app
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3002/health']
      interval: 5s
      timeout: 5s
      retries: 15
  payments:
    build:
      context: .
      dockerfile: ./apps/payments/Dockerfile
      target: development
    command: 'npm run start:dev payments'
    ports:
      - '4003:4003'
    volumes:
      - .:/usr/src/app
  notifications:
    build:
      context: .
      dockerfile: ./apps/notifications/Dockerfile
      target: development
    command: 'npm run start:dev notifications'
    ports:
      - '4004:4004'
    volumes:
      - .:/usr/src/app
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: 'npm run start:dev auth'
    ports:
      - '3001:3001'
      - '4001:4001'
    volumes:
      - .:/usr/src/app
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3001/health']
      interval: 5s
      timeout: 5s
      retries: 15
  mongo:
    image: mongo
  # rabbitmq:
  #   image: rabbitmq
  #   ports:
  #     - '5672:5672'
