services:
  e2e:
    build:
      context: ./e2e
      dockerfile: ./Dockerfile
    volumes:
      - ./e2e/specs:/usr/src/app/specs
    depends_on:
      - reservations
      - auth
      - payments
      - notifications
      - mongo
  reservations:
    build:
      context: .
      dockerfile: ./apps/reservation/Dockerfile
      target: development
    command: "npm run start:dev reservation"
    env_file:
      - ./apps/reservation/.env
    ports:
      - "3002:3002"
      - "4002:3002"
    volumes:
      - .:/usr/src/app
  payments:
    build:
      context: .
      dockerfile: ./apps/payments/Dockerfile
      target: development
    command: "npm run start:dev payments"
    env_file:
      - ./apps/payments/.env
    ports:
      - "4003:4003"
    volumes:
      - .:/usr/src/app
  notifications:
    build:
      context: .
      dockerfile: ./apps/notifications/Dockerfile
      target: development
    command: "npm run start:dev notifications"
    env_file:
      - ./apps/notifications/.env
    ports:
      - "4004:4004"
    volumes:
      - .:/usr/src/app
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: "npm run start:dev auth"
    env_file:
      - ./apps/auth/.env
    ports:
      - "3001:3001"
      - "4001:4001"
    volumes:
      - .:/usr/src/app
      
  mongo:
    image: mongo
